---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts

---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "79.5.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  values:
    prometheus:
      service:
        type: LoadBalancer
        port: 9090
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      service:
        type: LoadBalancer
        port: 9093
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

    grafana:
      enabled: true
      service:
        type: LoadBalancer
        port: 3000
      persistence:
        enabled: true
        storageClassName: openebs-jiva-default
        accessModes: ["ReadWriteOnce"]
        size: 5Gi
        annotations: {}
