apiVersion: v1
kind: Secret
metadata:
    name: auth-generic-oauth-secret
    namespace: observability
data:
    client_id: ENC[AES256_GCM,data:KaSc1VlKW3eAO6NozVO8XuHliWlgTiUjIRzGRw==,iv:eXhVPyv/XMLbQKOg3K+ERBEtW5swVFQzuUnLLlz81PQ=,tag:+R2hUJ0oyaEJXn4umC5oqw==,type:str]
    client_secret: ENC[AES256_GCM,data:+sg0AuuIA/t/G8s5yxT6xz6iYkiwk4vJwbL5LhMwTvOAcc2m,iv:R59LHuhrHaF7bioUQxHhm5W1Twg6MTaQ1Jjc71bXP4c=,tag:1Pt0weDnuI5qLf+HJ7dIqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zk2hpymtrjjffusejcpjkhuajccun96umdjyqx3p25ncn4zlzazq93eqdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ3J3R0NUOHcxT1dCZzNG
            bCs0R3NqeUVNbzN3am1YYlRHVzZZdG1ObkVJCklrMy9mTVBlbDVCclBXRVc2NWFj
            bjZYNm9zVEMxRWo0RktubnZXbGY2b00KLS0tIDg1Z0lDN1BEUkxzYi84NVhkSnUr
            UkhiU0toazRvaVpzTDh1bFJrZm5TVVkKhROInE4xeDantgyIcBq2hEnwwMIchiaw
            8mT4eQrO3nSmBcMN8sRiLRTDuro3evpmLZBEiyqTmC/eUpXfQF9+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T19:38:47Z"
    mac: ENC[AES256_GCM,data:i4WkBNrpBDfoukzs4dWryJudDiyGJvPhY4B+4WGtk9rHkzcn/f9BM3w1Myu/ex4Ergk2tebQd0o6TIfnOhoXc62eC3MPMWYcTmvPJn3whU1wXzyLcY+R/dPYPe8ti3PmqLPVxso7MJ/g17RlMOH4Z1Lg7XSQHSPf2x0wJHymy5I=,iv:cClyEStKWchAf6NDNuD554JCm5cQ9THxWjocfCoJLrY=,tag:fheorCP7wd1mfkksxxhzJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
