---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.30.0
  url: oci://ghcr.io/aquasecurity/helm-charts/trivy-operator
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: security
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system

  install:
    crds: CreateReplace

  upgrade:
    crds: CreateReplace
    cleanupOnFail: true

  values:
    serviceMonitor:
      enabled: true

    vulnerabilityReports:
      create: true

    configAuditReports:
      create: true

    trivy:
      ignoreUnfixed: true

      # PVC for the Trivy cache/db
      persistentvolumeclaims:
        create: true
        size: 10Gi
        storageClassName: openebs-hostpath

      persistentVolumeReclaimPolicy: Delete 

      # FIXED → This PVC was Pending
      server:
        storageClass: openebs-hostpath
        storage: 10Gi

    operator:
      builtInTrivyServer: true

    service:
      headless: false
