---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-secret
  namespace: wordpress
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    name: wordpress-secret
    creationPolicy: Owner

  data:
    - secretKey: wordpress-password
      remoteRef:
        key: wordpress
        property: WORDPRESS_PASSWORD

    - secretKey: mariadb-password
      remoteRef:
        key: wordpress
        property: MARIADB_PASSWORD

    - secretKey: mariadb-root-password
      remoteRef:
        key: wordpress
        property: MARIADB_ROOT_PASSWORD
